### ISSUE TITLE
Does nothing. iOS 14.4

### ISSUE THREAD

**Issue by swaggyP36000** [c22dev/Anonycord#1]
iPhone XS

App launches, and I can click start and stop, but there is no video in the camera roll. I also checked the app's data folder using Filza thinking maybe it saved something there and couldn't import it to the camera roll, but there is nothing in there either

Also, the app crashes when clicking the About tab and going back to the Record tab

**Comment by c22dev** [comment]
I know there is an issue with the process of switching from about page to the home page. The saving system is currently working, but I can't get the camera to work 😂 when 0.1 of TrollBox will be released and that my new app (secret) will work, I'll take back the development of Annonycord. Thanks for using my app, if you have knowing in Swift, feel free to contribute !

**Comment by c22dev** [comment]
now it's ready
