### ISSUE TITLE
button to press is small

### ISSUE THREAD

**Issue by anony159** [c22dev/Anonycord#13]
i changed a bit of code just to change the back camera to front camera, and it does work fine.
However the only problem seesm to be that the place to press to activate the screen recording and stop it seems to be a very tiny space in the middle, have any idea how to increase that space.

**Comment by c22dev** [comment]
It should be a Rectangle element in a button.
Try making the rectangle take all the space and ignore safe zone/edges.

I'll try to send you some code snippets tonight.

**Comment by anony159** [comment]
thanks im just new to coding and still learning, but just found it weird that the place to press goes smaller when the camera is changed

**Comment by anony159** [comment]
let recordButton = UIButton(frame: CGRect(x: 0, y: 0, width: 70, height: 70))
        recordButton.center = view.center

is that the code for the space to press?

**Comment by c22dev** [comment]
prob is.
It's been a year since I touched at this code, considering the variable name I'd say it is.
Not the project I am the most proud of tbh...
