### ISSUE TITLE
App crashes when trying to record 14.2

### ISSUE THREAD

**Issue by null-socks** [c22dev/Anonycord#2]
I accepted all the requests (camera, audio, and camera roll) and tried every version on the release tab but as soon as I try to record, it crashes.

iPhone Se gen 2 on ios 14.2

**Comment by c22dev** [comment]
Hey there !! Can you provide more details ? Do it crash instantly after launch ?? Because if it’s after 2 clicks, it’s normal. Click 1 time and wait for 5sec, then click back. You should see smth on camera roll hopefully

**Comment by null-socks** [comment]
Ah, I see. It works as intended I guess
