### ISSUE TITLE
Crashes when I double tap to save it on gallery

### ISSUE THREAD

**Issue by yehonatan5f** [c22dev/Anonycord#5]
I'm on iOS 15.1 and I tried to open the app, it did open and I gave it the permissions that It asked for, after giving it a permission to the whole photo library, it just kept crashing when I double tap to save the video and then it saves 0 seconds of the video...

**Comment by c22dev** [comment]
Tap 1 time, and the video starts recording. When you tap the second time, it stops. Read the instructions!
